---
- name: Ensure monitor daemon is started
  systemd:
    name: "ceph-mon@{{ monitor_name }}"
    state: started
    enabled: yes
  when: containerized_deployment | bool

- name: Wait for monitor socket to exist
  wait_for:
    path: "/var/run/ceph/{{ cluster }}-mon.{{ monitor_name }}.asok"
    timeout: 30
  when: containerized_deployment | bool

- name: Waiting for the monitor(s) to form the quorum...
  command: >
    {{ container_exec_cmd | default('') }}
    ceph
    --cluster {{ cluster }}
    --admin-daemon /var/run/ceph/{{ cluster }}-mon.{{ ansible_hostname }}.asok
    mon_status
    --format json
  register: ceph_health_raw
  until: >
    (ceph_health_raw.stdout | length > 0) and
    (ceph_health_raw.stdout | from_json).state in ['leader', 'peon']
  retries: 20
  delay: 10
  changed_when: false
  failed_when: false

- name: Show monitor status
  debug:
    var: ceph_health_raw.stdout
  when: ceph_health_raw.stdout is defined

- name: Fetch ceph initial keys
  ceph_key:
    state: fetch_initial_keys
    cluster: "{{ cluster }}"
    owner: "{{ ceph_uid if containerized_deployment | bool else 'ceph' }}"
    group: "{{ ceph_uid if containerized_deployment | bool else 'ceph' }}"
    mode: "0400"
  environment:
    CEPH_CONTAINER_IMAGE: "{{ ceph_docker_registry + '/' + ceph_docker_image + ':' + ceph_docker_image_tag if containerized_deployment | bool else None }}"
    CEPH_CONTAINER_BINARY: "{{ container_binary }}"
  register: key_result
  until: key_result is success
  retries: 5
  delay: 10
  no_log: "{{ no_log_on_ceph_key_tasks }}"
  when:
    - cephx | bool
