---
- name: Create systemd override directory
  file:
    path: "/etc/systemd/system/ceph-mon.service.d"
    state: directory
    owner: "root"
    group: "root"
    mode: "0755"

- name: Add ceph-mon systemd service overrides
  template:
    src: "ceph-mon.service.d/override.conf.j2"
    dest: "/etc/systemd/system/ceph-mon.service.d/override.conf"
    owner: "root"
    group: "root"
    mode: "0644"
  notify: restart ceph mons

- name: Include_tasks systemd.yml
  ansible.builtin.include_tasks: systemd.yml
  when: containerized_deployment | bool

- name: Start the monitor service
  ansible.builtin.systemd:
    name: ceph-mon@{{ monitor_name if not containerized_deployment | bool else ansible_facts['hostname'] }}
    state: started
    enabled: true
    masked: false
    daemon_reload: true
