---
- name: Create ceph configuration directory
  file:
    path: /etc/ceph
    state: directory
    mode: '0755'

- name: Configure ceph.conf
  template:
    src: ceph.conf.j2
    dest: /etc/ceph/ceph.conf
    mode: '0644'

- name: Install required packages
  package:
    name: 
      - ceph
      - ceph-common
    state: present
